//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPréstamos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Avalan
    {
        public int Folio { get; set; }
        public int IdAval { get; set; }
        public Nullable<decimal> MontoAvalado { get; set; }
    
        public virtual Préstamos Préstamos { get; set; }
        public virtual Avales Avales { get; set; }

      //Constructores.
      public Avalan() { }
      public Avalan(int Folio, int IdAval, decimal MontoAvalado)  {
        this.Folio = Folio; this.IdAval = IdAval; this.MontoAvalado = MontoAvalado;
      }
    }
}
