//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPréstamos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Préstamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Préstamos()
        {
            this.Avalan = new ObservableCollection<Avalan>();
            this.Pagos = new ObservableCollection<Pagos>();
        }
    
        public int Folio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<float> Tasa { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<decimal> Mensualidad { get; set; }
        public Nullable<decimal> PagoTotal { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string RFC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Avalan> Avalan { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Pagos> Pagos { get; set; }
    }
}
